### ISSUE TITLE
Fails on JSX files

### ISSUE THREAD

**Issue by jyasskin** [renke/atom-import-sort#1]
It looks like the parser is trying to parse the entire file before sorting the import section at the top, and it fails on unrecognized syntax. It'd be nice if it could stop parsing at the end of the imports to avoid getting confused.

**Comment by renke** [comment]
Yes, that's true. It's currently using Babel to parse Javascript files and it parses the entire file. I am not sure if Babel can deal with invalid syntax in a streaming manner, but I am going to look into it. Now that I think about it the "Failed to sort imports" warning should be disabled for sort on save.

By the way, the title says JSX files, do you only have problems with those? JSX is definitely supported because of Babel.

**Comment by jyasskin** [comment]
And it has started working now. I'm not sure what I did wrong.
