### ISSUE TITLE
sort rule changed after update

### ISSUE THREAD

**Issue by Murriouz** [renke/atom-import-sort#10]
Here's what's the imports looks before:

![image](https://cloud.githubusercontent.com/assets/4125903/19099818/7f34a2ae-8aec-11e6-93bd-d13d8fbaa725.png)

After update, the imports become this (after save):

![image](https://cloud.githubusercontent.com/assets/4125903/19099830/98b52a32-8aec-11e6-845f-80bb73f420d5.png)

Don't know what happened.

Sort on save turned on.

Wether have config in package.json have not effect on this issue.

**Comment by renke** [comment]
In version 2 the default style was changed to match ESLint's [sort-imports rule](http://eslint.org/docs/rules/sort-imports). That's why you see that result.

You can use `import-sort-style-renke` to get a style that is similar to the old one. Just install it in your project with `npm install --save-dev import-sort-style-renke` and add the following to your `package.json`:

```
"importSort": {
  ".js, .jsx, .es6, .es": {
    "parser": "babylon",
    "style": "renke"
  }
}
```

Let me know if that works for you!

**Comment by Murriouz** [comment]
It works. But it's similar but a bit different.
This change make a bit chaos to our git repo (makes a lot of changes).
Is there any chance to write our own rules?

**Comment by renke** [comment]
Yes, when I find time, I will create a style that replicates exactly the old style. Sorry, for the inconvenience. I let you know when it's done.

**Comment by Murriouz** [comment]
That's very kind of you. Thanks.

**Comment by renke** [comment]
@Murriouz I just updated `import-sort-style-renke` (and `atom-import-sort`) to be more like the old style. Please let me know if works better for you!

**Comment by Murriouz** [comment]
@renke Thanks for your great work! It's just like old style. Thanks again.
